name: Deploy to EC2

on:
  push:
    branches:
      - master  # This triggers on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 65.2.5.28 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@65.2.5.28 << 'EOF'
          cd /home/ubuntu/test-project   # Ensure this folder exists and the repo is cloned
          git pull origin master          # Correct branch name (master)
          ./mvnw clean package
          pkill -f 'java' || true
          nohup java -jar target/*.jar > app.log 2>&1 &
        EOF
